<?php

namespace SmoDav\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = ['name', 'phone_number', 'email', 'account_number', 'address'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created( function ($model){
            $model->account_number = 'CLI-' . $model->id;
            $model->save();
        });
    }

}
