<?php

namespace SmoDav\Models;

use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Self_;

class UserGroup extends Model
{
    const PERM_USER_FULL_ACCESS = 'users_full_access';
    const PERM_ROLES_FULL_ACCESS = 'roles_full_access';
    const PERM_TRANSACTION_APPROVE = 'transaction_make';
    const PERM_TRANSACTION_VIEW = 'transaction_view';
    const PERM_PETTY_CASH_FULL_ACCESS = 'petty_full_access';
    const PERM_STALL_ASSIGNMENT = 'stall_full_access';
    const CACHE_KEY = 'USER_GROUP';

    protected $fillable = ['name', 'permissions'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::updated(
            function () {
                recacheRoles();
            });

        self::created(
            function () {
                recacheRoles();
            });

        self::deleted(
            function () {
                recacheRoles();
            });
    }
}
