<link href="{{ asset('assets/libs/jqueryui/ui-lightness/jquery-ui-1.10.4.custom.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/fontello/css/fontello.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/animate-css/animate.min.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/nifty-modal/css/component.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/magnific-popup/magnific-popup.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/ios7-switch/ios7-switch.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/pace/pace.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/sortable/sortable-theme-bootstrap.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/bootstrap-datepicker/css/datepicker.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/libs/jquery-icheck/skins/all.css') }}" rel="stylesheet" />